baseURL = "https://justloaves.netlify.app"
languageCode = "en-us"
title = "Just Loaves"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo3.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo3.svg"
    desktop_height = "300px"
    desktop_width = "300px"
    alt = "Just Loaves"

  [params.homepage_meta_tags]
    meta_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."
    meta_og_title = "Just Loaves"
    meta_og_type = "website"
    meta_og_url = "https://justloaves.netlify.app"
    meta_og_image = "https://justloaves.netlify.app/images/logo3.svg"
    meta_og_description = "Just Loaves by Kirtsi"


[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
